export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
}

export const quizData: Record<string, QuizQuestion[]> = {
  'js-basics': [
    { question: 'Which keyword is used to declare a variable in JavaScript?', options: ['var', 'let', 'const', 'All of the above'], correct: 3 },
    { question: 'What is the output of typeof null?', options: ['null', 'object', 'undefined', 'boolean'], correct: 1 },
    { question: 'Which method adds an element to the end of an array?', options: ['pop()', 'push()', 'shift()', 'unshift()'], correct: 1 },
    { question: 'What does === compare?', options: ['Value only', 'Type only', 'Value and type', 'Reference'], correct: 2 },
    { question: 'How do you write a comment in JavaScript?', options: ['// comment', '# comment', '/* comment */', 'Both // and /* */'], correct: 3 },
    { question: 'What is a closure?', options: ['A function inside a function', 'A closed variable', 'A loop construct', 'An array method'], correct: 0 },
    { question: 'Which method converts JSON to a JS object?', options: ['JSON.stringify()', 'JSON.parse()', 'JSON.convert()', 'JSON.toObject()'], correct: 1 },
    { question: 'What is the result of 2 + "2"?', options: ['4', '"22"', '22', 'Error'], correct: 1 },
    { question: 'Which loop runs at least once?', options: ['for', 'while', 'do...while', 'forEach'], correct: 2 },
    { question: 'What does NaN stand for?', options: ['Not a Number', 'Null and Nil', 'No Assignment Needed', 'None'], correct: 0 },
  ],
  'react-fundamentals': [
    { question: 'What is React?', options: ['A database', 'A UI library', 'A CSS framework', 'A build tool'], correct: 1 },
    { question: 'Which hook manages state?', options: ['useEffect', 'useState', 'useContext', 'useRef'], correct: 1 },
    { question: 'What is JSX?', options: ['JavaScript XML', 'JSON extension', 'Java syntax', 'CSS syntax'], correct: 0 },
    { question: 'How do you pass data to a component?', options: ['state', 'props', 'refs', 'store'], correct: 1 },
    { question: 'Which method renders a React app?', options: ['React.start()', 'React.render()', 'createRoot().render()', 'React.mount()'], correct: 2 },
    { question: 'What is the virtual DOM?', options: ['The real DOM', 'A copy of the DOM in memory', 'A database', 'A server'], correct: 1 },
    { question: 'Which hook runs after render?', options: ['useState', 'useEffect', 'useMemo', 'useReducer'], correct: 1 },
    { question: 'What is a React component?', options: ['A function returning JSX', 'A CSS class', 'An HTML file', 'A database table'], correct: 0 },
    { question: 'How do you conditionally render in React?', options: ['if/else', 'ternary operator', '&& operator', 'All of the above'], correct: 3 },
    { question: 'What does useState return?', options: ['A single value', 'An array [value, setter]', 'An object', 'A promise'], correct: 1 },
  ],
  'node-api': [
    { question: 'What is Node.js?', options: ['A frontend framework', 'A runtime for JavaScript', 'A database', 'A CSS preprocessor'], correct: 1 },
    { question: 'Which module creates a server?', options: ['fs', 'path', 'http', 'os'], correct: 2 },
    { question: 'What is Express?', options: ['A database', 'A web framework for Node.js', 'A templating engine', 'A build tool'], correct: 1 },
    { question: 'What does CRUD stand for?', options: ['Create, Read, Update, Delete', 'Copy, Run, Update, Deploy', 'Compile, Render, Use, Debug', 'None'], correct: 0 },
    { question: 'Which HTTP method updates data?', options: ['GET', 'POST', 'PUT', 'DELETE'], correct: 2 },
    { question: 'What is middleware?', options: ['A database query', 'A function that processes requests', 'A CSS framework', 'A type of loop'], correct: 1 },
    { question: 'How do you parse JSON in Express?', options: ['express.json()', 'express.parse()', 'express.body()', 'express.data()'], correct: 0 },
    { question: 'What is npm?', options: ['Node Package Manager', 'Next Process Manager', 'New Programming Model', 'None'], correct: 0 },
    { question: 'Which status code means "Not Found"?', options: ['200', '301', '404', '500'], correct: 2 },
    { question: 'What is a REST API?', options: ['A database', 'A stateless API using HTTP', 'A CSS framework', 'A JavaScript library'], correct: 1 },
  ],
  'python-data': [
    { question: 'Which library is used for data manipulation in Python?', options: ['NumPy', 'Pandas', 'Matplotlib', 'Scikit-learn'], correct: 1 },
    { question: 'How do you read a CSV file with Pandas?', options: ['pd.read_csv()', 'pd.load_csv()', 'pd.open_csv()', 'pd.import_csv()'], correct: 0 },
    { question: 'What does df.head() return?', options: ['Last 5 rows', 'First 5 rows', 'All rows', 'Column names'], correct: 1 },
    { question: 'Which library is used for plotting?', options: ['Pandas', 'NumPy', 'Matplotlib', 'Seaborn'], correct: 2 },
    { question: 'What is a DataFrame?', options: ['A 1D array', 'A 2D labeled data structure', 'A database', 'A function'], correct: 1 },
    { question: 'How do you select a column in Pandas?', options: ['df.column_name', "df['column_name']", 'Both', 'df.get()'], correct: 2 },
    { question: 'What does df.isnull() do?', options: ['Drops nulls', 'Finds missing values', 'Fills nulls', 'Counts rows'], correct: 1 },
    { question: 'Which function computes the mean?', options: ['df.median()', 'df.mean()', 'df.mode()', 'df.sum()'], correct: 1 },
    { question: 'What is NumPy used for?', options: ['Plotting', 'Numerical computing', 'Web scraping', 'Machine learning'], correct: 1 },
    { question: 'How do you group data in Pandas?', options: ['df.group()', 'df.groupby()', 'df.cluster()', 'df.sort()'], correct: 1 },
  ],
  'git-workflow': [
    { question: 'What is Git?', options: ['A programming language', 'A version control system', 'A database', 'A text editor'], correct: 1 },
    { question: 'Which command stages changes?', options: ['git commit', 'git push', 'git add', 'git status'], correct: 2 },
    { question: 'What does git commit do?', options: ['Saves changes locally', 'Uploads to remote', 'Deletes files', 'Creates a branch'], correct: 0 },
    { question: 'How do you create a new branch?', options: ['git branch new-branch', 'git checkout -b new-branch', 'Both', 'git create branch'], correct: 2 },
    { question: 'What is a pull request?', options: ['A request to pull code', 'A request to merge changes', 'A request to delete', 'A bug report'], correct: 1 },
    { question: 'Which command updates local repo?', options: ['git push', 'git pull', 'git commit', 'git merge'], correct: 1 },
    { question: 'What does git status show?', options: ['Commit history', 'Current branch state', 'Remote URL', 'Installed tools'], correct: 1 },
    { question: 'How do you undo a staged file?', options: ['git reset', 'git revert', 'git checkout', 'git clean'], correct: 0 },
    { question: 'What is a merge conflict?', options: ['When branches have diverging changes', 'A server error', 'A login issue', 'A network problem'], correct: 0 },
    { question: 'Which file tracks what to ignore?', options: ['.gitignore', '.gitconfig', '.gitkeep', '.gitfiles'], correct: 0 },
  ],
  'html-css': [
    { question: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'None'], correct: 0 },
    { question: 'Which tag creates a hyperlink?', options: ['<link>', '<a>', '<href>', '<url>'], correct: 1 },
    { question: 'What does CSS stand for?', options: ['Cascading Style Sheets', 'Creative Style System', 'Computer Style Sheets', 'None'], correct: 0 },
    { question: 'How do you center a div horizontally?', options: ['margin: 0 auto', 'text-align: center', 'align: center', 'Both margin and text-align'], correct: 0 },
    { question: 'Which property makes a flex container?', options: ['display: block', 'display: flex', 'display: inline', 'display: grid'], correct: 1 },
    { question: 'What is the box model?', options: ['Content, padding, border, margin', 'Header, nav, main, footer', 'HTML, CSS, JS, DOM', 'None'], correct: 0 },
    { question: 'Which tag is used for an image?', options: ['<img>', '<image>', '<pic>', '<src>'], correct: 0 },
    { question: 'What does responsive design mean?', options: ['Design that responds to screen size', 'Design with animations', 'Fast loading design', 'None'], correct: 0 },
    { question: 'Which unit is relative to the parent font size?', options: ['px', 'em', 'rem', 'vh'], correct: 1 },
    { question: 'What is media queries used for?', options: ['Responsive design', 'Animations', 'Colors', 'Fonts'], correct: 0 },
  ],
  'typescript': [
    { question: 'What is TypeScript?', options: ['A CSS framework', 'A typed superset of JavaScript', 'A database', 'A build tool'], correct: 1 },
    { question: 'How do you define a type?', options: ['type', 'interface', 'Both', 'class'], correct: 2 },
    { question: 'What does : number mean?', options: ['A type annotation', 'A comment', 'A variable name', 'A function'], correct: 0 },
    { question: 'What is the any type?', options: ['Any value allowed', 'No value', 'Unknown type', 'None'], correct: 0 },
    { question: 'How do you make a property optional?', options: ['?', '!', '*', '_'], correct: 0 },
    { question: 'What does TypeScript compile to?', options: ['Python', 'JavaScript', 'Java', 'C++'], correct: 1 },
    { question: 'What is an interface?', options: ['A contract for object shape', 'A CSS class', 'A database table', 'A function'], correct: 0 },
    { question: 'What does readonly mean?', options: ['Cannot be changed after init', 'Can only be read', 'Visible everywhere', 'None'], correct: 0 },
    { question: 'How do you define a union type?', options: ['|', '&', '||', '&&'], correct: 0 },
    { question: 'What is the main benefit of TypeScript?', options: ['Type safety', 'Faster runtime', 'Smaller bundles', 'Better styling'], correct: 0 },
  ],
  'nextjs': [
    { question: 'What is Next.js?', options: ['A React framework', 'A CSS framework', 'A database', 'A build tool'], correct: 0 },
    { question: 'How do you create a page in Next.js?', options: ['Create a file in pages/', 'Create a file in app/', 'Add a route in config', 'Both pages/ and app/'], correct: 3 },
    { question: 'What is SSR?', options: ['Server-Side Rendering', 'Client-Side Rendering', 'Static Site Generation', 'None'], correct: 0 },
    { question: 'How do you fetch data in a server component?', options: ['useEffect', 'async/await', 'componentDidMount', 'useState'], correct: 1 },
    { question: 'What is the App Router?', options: ['The new routing system', 'A navigation library', 'A CSS utility', 'A database tool'], correct: 0 },
    { question: 'How do you create an API route?', options: ['Create route.ts in app/api/', 'Add a controller file', 'Install a plugin', 'Use Express'], correct: 0 },
    { question: 'What is a layout in Next.js?', options: ['A shared UI wrapper', 'A CSS grid', 'A database schema', 'A TypeScript type'], correct: 0 },
    { question: 'What does next/link do?', options: ['Client-side navigation', 'Server redirect', 'CSS linking', 'Database connection'], correct: 0 },
    { question: 'What is static generation?', options: ['Pre-rendered HTML at build time', 'Dynamic rendering', 'Server-side rendering', 'None'], correct: 0 },
    { question: 'Which command starts the dev server?', options: ['npm run dev', 'npm start', 'npm build', 'npm serve'], correct: 0 },
  ],
  'sql-basics': [
    { question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Language', 'Standard Query Language', 'None'], correct: 0 },
    { question: 'Which command retrieves data?', options: ['INSERT', 'SELECT', 'UPDATE', 'DELETE'], correct: 1 },
    { question: 'How do you filter records?', options: ['WHERE', 'HAVING', 'FILTER', 'Both WHERE and HAVING'], correct: 3 },
    { question: 'What is a primary key?', options: ['A unique identifier', 'A foreign reference', 'An index', 'A constraint'], correct: 0 },
    { question: 'Which JOIN returns matching rows from both tables?', options: ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN'], correct: 2 },
    { question: 'What does COUNT(*) do?', options: ['Counts rows', 'Counts non-null values', 'Counts columns', 'Sums values'], correct: 0 },
    { question: 'How do you sort results?', options: ['ORDER BY', 'SORT BY', 'GROUP BY', 'ARRANGE BY'], correct: 0 },
    { question: 'What is a foreign key?', options: ['A key from another table', 'A primary key', 'An index', 'A constraint'], correct: 0 },
    { question: 'Which command adds new data?', options: ['INSERT INTO', 'ADD INTO', 'CREATE', 'PUT'], correct: 0 },
    { question: 'What does NULL mean?', options: ['Missing value', 'Zero', 'Empty string', 'False'], correct: 0 },
  ],
  'docker': [
    { question: 'What is Docker?', options: ['A container platform', 'A database', 'A programming language', 'A text editor'], correct: 0 },
    { question: 'What is a Dockerfile?', options: ['A file with instructions to build an image', 'A config file', 'A log file', 'A network config'], correct: 0 },
    { question: 'Which command runs a container?', options: ['docker build', 'docker run', 'docker start', 'docker create'], correct: 1 },
    { question: 'What is an image?', options: ['A running container', 'A snapshot for containers', 'A Dockerfile', 'A volume'], correct: 1 },
    { question: 'What is Docker Compose?', options: ['Multi-container orchestration', 'A single container tool', 'A monitoring tool', 'A registry'], correct: 0 },
    { question: 'Which command lists running containers?', options: ['docker ps', 'docker ls', 'docker status', 'docker list'], correct: 0 },
    { question: 'What is a volume?', options: ['Persistent data storage', 'A container', 'An image', 'A network'], correct: 0 },
    { question: 'What does FROM do in a Dockerfile?', options: ['Sets the base image', 'Copies files', 'Installs packages', 'Sets environment'], correct: 0 },
    { question: 'Which command builds an image?', options: ['docker build', 'docker create', 'docker make', 'docker compile'], correct: 0 },
    { question: 'What is a container?', options: ['A running instance of an image', 'A virtual machine', 'A Dockerfile', 'A volume'], correct: 0 },
  ],
};

export function getTopicName(id: string): string {
  const names: Record<string, string> = {
    'js-basics': 'JavaScript Basics',
    'react-fundamentals': 'React Fundamentals',
    'node-api': 'Node.js API Design',
    'python-data': 'Python for Data Science',
    'git-workflow': 'Git & Collaboration',
    'html-css': 'HTML & CSS Essentials',
    'typescript': 'TypeScript Deep Dive',
    'nextjs': 'Next.js Full Stack',
    'sql-basics': 'SQL & Databases',
    'docker': 'Docker & Containers',
  };
  return names[id] || id;
}
