"""Generative AI mode (Feature: LLM-generated roles & paths).

When the grounded catalogue has no good fit — or the intern asks for it — Gemini
generates bespoke roles and a learning path from the intern's free-text skills and
interests. Output is clearly labelled as AI-generated and must be reviewed by a human
(the constitution: "AI output is reviewed", "suggestions, not verdicts").

This module is entirely optional: it requires a GEMINI_API_KEY. If none is present it
returns empty results / raises, and the app falls back to the grounded path.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import List

from .config import gemini_available

GENERATION_MODEL = "gemini-3.6-flash"

GENERATED_DISCLAIMER = (
    "These roles and paths were generated by AI from your input and are "
    "suggestions to explore — verify them before treating them as accurate, and "
    "treat them as a starting point, not a destiny."
)


@dataclass
class GeneratedRole:
    title: str
    why: str
    matched_skills: List[str] = field(default_factory=list)
    missing_skills: List[str] = field(default_factory=list)


@dataclass
class GeneratedMilestone:
    order: int
    skill: str
    title: str
    resources: List[str] = field(default_factory=list)
    rationale: str = ""


@dataclass
class GeneratedResult:
    roles: List[GeneratedRole]
    path: List[GeneratedMilestone]
    disclaimer: str = GENERATED_DISCLAIMER


class GeminiNotAvailableError(Exception):
    """No GEMINI_API_KEY present — generative mode cannot run."""


def _client():
    if not gemini_available():
        raise GeminiNotAvailableError(
            "Generative AI needs a GEMINI_API_KEY. Add one to your .env to use this."
        )
    from google import genai
    from google.genai import types

    return genai.Client(api_key=os.environ["GEMINI_API_KEY"]), types


def _extract_json(text: str):
    # tolerate fenced JSON
    t = text
    if "```" in t:
        parts = t.split("```")
        for p in parts:
            if "{" in p and "}" in p:
                t = p.strip().lstrip("json").strip()
                break
    return json.loads(t)


def _known_skill_hints() -> str:
    # Light grounding: pass the catalogue's real skills so generated content stays
    # loosely plausible, but the LLM may add new ones (that's the point of this mode).
    from .normalize import load_catalogue

    cat = load_catalogue("data/catalogue.json")
    return ", ".join(sorted(cat.skill_names))


def generate(skills: List[str], interests: List[str], top_n: int = 3) -> GeneratedResult:
    """Ask Gemini to generate bespoke roles and a learning path for one top role.

    Raises GeminiNotAvailableError if no key; returns a parsed GeneratedResult.
    On an LLM error, lets the exception propagate (caller shows a clear message) —
    never a partial/hallucinated parse.
    """
    client, types = _client()
    skills_txt = ", ".join(skills) or "(none provided)"
    interests_txt = ", ".join(interests) or "(none provided)"

    prompt = f"""
You are a career-guidance assistant. Based on an intern's skills and interests,
invent {top_n} plausible, real-world job roles they could pursue — do NOT restrict
yourself to any fixed list. For each role give a short "why" in plain language, a list
of matched skills (those the intern likely already has), and a list of missing skills.

For the SINGLE most promising role, also give a concise, ordered learning path
(5 milestones): each milestone has a skill to learn, a short title, a one-line
rationale, and up to 2 reputable resource suggestions.

Useful known skills in the domain (you may add new ones): {_known_skill_hints()}

Return ONLY JSON, no prose, exactly this shape:
{{
  "roles": [
    {{"title": "...", "why": "...", "matched_skills": ["..."], "missing_skills": ["..."]}}
  ],
  "path": [
    {{"skill": "...", "title": "...", "rationale": "...", "resources": ["...", "..."]}}
  ]
}}

Intern skills: {skills_txt}
Intern interests: {interests_txt}
"""
    resp = client.models.generate_content(
        model=GENERATION_MODEL,
        config=types.GenerateContentConfig(
            system_instruction=(
                "You generate career suggestions groundedly but creatively. Output is "
                "JSON only. Keep content plausible and kind; never present any role as "
                "a guarantee."
            ),
            temperature=0.7,
            response_mime_type="application/json",
        ),
        contents=prompt,
    )
    data = _extract_json(resp.text or "{}")

    roles = [
        GeneratedRole(
            title=str(r.get("title", "")).strip(),
            why=str(r.get("why", "")).strip(),
            matched_skills=[str(s) for s in r.get("matched_skills", [])],
            missing_skills=[str(s) for s in r.get("missing_skills", [])],
        )
        for r in data.get("roles", [])
        if str(r.get("title", "")).strip()
    ]
    path = [
        GeneratedMilestone(
            order=i,
            skill=str(m.get("skill", "")).strip(),
            title=str(m.get("title", "")).strip(),
            rationale=str(m.get("rationale", "")).strip(),
            resources=[str(x) for x in m.get("resources", [])],
        )
        for i, m in enumerate(data.get("path", []), start=1)
        if str(m.get("title", "")).strip()
    ]
    return GeneratedResult(roles=roles, path=path)
